server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /business
spring:
  application:
    name: business
  datasource:
#    url: jdbc:mysql://localhost:3306/poi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: 123
#    driver-class-name: com.mysql.cj.jdbc.Driver
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/mp?serverTimezone=Asia/Shanghai
     username: postgres
     password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    registry-fetch-interval-seconds: 10 #拉取服务注册信息间隔时间（默认为30s）
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30 #每隔30s发送一次心跳
    lease-expiration-duration-in-seconds: 90 #告知服务端90秒还未收到心跳的话，就将该服务移除列表

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.core.model.business
  global-config:
    db-config:
      id-type: auto
